# Generated by Django 3.2.6 on 2021-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=500)),
                ('text_content', models.TextField(max_length=2000)),
                ('html_content', models.TextField(max_length=4000)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
