# Generated by Django 3.2.6 on 2021-09-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='text_content',
        ),
    ]
